import { z } from "zod";
import { asChainId } from "../ids.js";
import { TaskPrioritySchema } from "../enums.js";

// ── Legacy format (deprecated) ────────────────────────────────────────

export const ChainTaskDefSchema = z.object({
  title: z.string(),
  description: z.string(),
  criteria: z.string(),
  priority: TaskPrioritySchema,
});
/** @deprecated Use ChainTask instead. */
export type ChainTaskDef = z.infer<typeof ChainTaskDefSchema>;

// ── New format: dynamic tasks with system_prompt ──────────────────────

/**
 * Quality gate for a chain task. Determines how the task's output
 * is validated before the chain proceeds to the next task.
 */
export const QualityGateSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("self_eval"),
    criteria: z.string(),
  }),
  z.object({
    type: z.literal("test"),
    criteria: z.string(),
    /** Shell commands to run as part of the gate (e.g. ["pnpm test"]). */
    commands: z.array(z.string()).default([]),
  }),
  z.object({
    type: z.literal("review"),
    criteria: z.string(),
    /** Prompt sent to the reviewer LLM. */
    reviewer_prompt: z.string().default(""),
  }),
  z.object({
    type: z.literal("accept"),
    criteria: z.string(),
    /** Prompt sent to the acceptor LLM. */
    acceptor_prompt: z.string().default(""),
  }),
]);
export type QualityGate = z.infer<typeof QualityGateSchema>;

/**
 * A single task in a chain, with a dynamically generated system prompt.
 *
 * Leader generates the system_prompt to tell the Worker *how* to execute
 * the task, rather than relying on fixed role-based templates.
 */
export const ChainTaskSchema = z.object({
  /** Unique task identifier within the chain. */
  task_id: z.string(),
  /** Human-readable task title. */
  title: z.string(),
  /** Task description (what needs to be done). */
  description: z.string(),
  /** Leader-generated system prompt (how to do it). */
  system_prompt: z.string(),
  /** Task IDs that must complete before this task can start. */
  depends_on: z.array(z.string()).default([]),
  /** Task priority (0 = lowest, 2 = highest). */
  priority: TaskPrioritySchema.default(1),
  /** Success criteria for the task. */
  criteria: z.string().default(""),
  /** Optional quality gate for validating task output. */
  quality_gate: QualityGateSchema.optional(),
});
export type ChainTask = z.infer<typeof ChainTaskSchema>;

// ── ChainDef: accepts both legacy and new formats ─────────────────────

/**
 * Legacy ChainDef with fixed link-type keys (plan, execute, verify, etc.).
 * @deprecated Use the new ChainDef format with `task_list` instead.
 */
export const LegacyChainDefSchema = z.object({
  chain_id: z.string().transform(asChainId),
  chain_title: z.string(),
  tasks: z.object({
    plan: ChainTaskDefSchema.nullable(),
    execute: ChainTaskDefSchema,
    verify: ChainTaskDefSchema,
    review: ChainTaskDefSchema,
    accept: ChainTaskDefSchema,
    explore: ChainTaskDefSchema.optional(),
  }),
});

/**
 * New ChainDef with a generic list of tasks, each carrying its own
 * system_prompt generated by the Leader.
 */
export const NewChainDefSchema = z.object({
  chain_id: z.string().transform(asChainId),
  chain_title: z.string(),
  /** Ordered list of tasks. Leader determines execution order via depends_on. */
  task_list: z.array(ChainTaskSchema).min(1),
});

/**
 * ChainDef accepts either the legacy format (fixed link-type keys) or
 * the new format (generic task_list with system_prompt).
 */
export const ChainDefSchema = z.union([NewChainDefSchema, LegacyChainDefSchema]);
export type ChainDef = z.infer<typeof ChainDefSchema>;
export type LegacyChainDef = z.infer<typeof LegacyChainDefSchema>;
export type NewChainDef = z.infer<typeof NewChainDefSchema>;
