// CORE-RETENTION
// Locks in: CommitChecker passes the commit message to `git commit` as a
//   separate argv element (via execFileSync), so shell metacharacters in the
//   message — backticks, $(), quotes, semicolons — cannot escape into the
//   parent shell. The literal message is preserved in the commit object.
// Core path because: commit messages are generated by claude-cli output and
//   travel directly into a child process; any shell-interpolation regression
//   becomes an arbitrary code execution sink in every Worker worktree.
// Owner subsystem: worker.
// Primary source files exercised:
//   - packages/worker/src/commit-checker.ts
//
// TRUST-JUSTIFICATION: this test fakes IClaudeRunner so claude-cli is not
//   invoked, and uses a real on-disk git repo + real `git` binary. The injected
//   commit message is the protocol contract between CommitChecker and git —
//   we verify the literal message is preserved and no shell side-effect file
//   was created.
// Downstream: the actual claude-cli generation of commit messages is covered
//   by tests/core/manual/claude-cli-smoke.mjs.

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { execFileSync } from "node:child_process";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  asInstanceId,
  asTaskId,
  type IClaudeRunner,
  type ILogger,
  type RunOptions,
  type RunResult,
} from "@co/contracts";
import { TemplateEngine } from "@co/runtime";
import { CommitChecker } from "../../../src/commit-checker.js";

class SilentLogger implements ILogger {
  debug(): void {}
  info(): void {}
  warn(): void {}
  error(): void {}
  child(): ILogger {
    return this;
  }
}

class FixedRunner implements IClaudeRunner {
  constructor(private readonly out: string) {}
  async run(opts: RunOptions): Promise<RunResult> {
    fs.mkdirSync(path.dirname(opts.log_path), { recursive: true });
    fs.writeFileSync(opts.log_path, this.out);
    return { exit_code: 0, session_id: null, log_path: opts.log_path };
  }
}

function newTemplateEngine(): TemplateEngine {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "commit-tpl-"));
  fs.writeFileSync(
    path.join(dir, "worker-commit-message.md"),
    "msg for {{task_title}} ({{link}})",
  );
  return new TemplateEngine({ primary_dir: dir });
}

function initRepo(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "commit-repo-"));
  execFileSync("git", ["init", "-q", "-b", "main"], { cwd: dir });
  execFileSync("git", ["config", "user.email", "t@t"], { cwd: dir });
  execFileSync("git", ["config", "user.name", "t"], { cwd: dir });
  execFileSync("git", ["config", "commit.gpgsign", "false"], { cwd: dir });
  fs.writeFileSync(path.join(dir, "seed.txt"), "seed");
  execFileSync("git", ["add", "."], { cwd: dir });
  execFileSync("git", ["commit", "-q", "-m", "seed"], { cwd: dir });
  return dir;
}

function makeChecker(repo: string, runnerOut: string): CommitChecker {
  const cacheDir = fs.mkdtempSync(path.join(os.tmpdir(), "commit-cache-"));
  return new CommitChecker({
    worktree_path: repo,
    runner: new FixedRunner(runnerOut),
    template_engine: newTemplateEngine(),
    logger: new SilentLogger(),
    cache_paths: {
      cache_dir: cacheDir,
      leader_instance_id: asInstanceId("leader-1"),
    },
    worker_name: "Tester",
  });
}

describe("CommitChecker shell-safety", () => {
  const sentinel = path.join(os.tmpdir(), `co-commit-sentinel-${Date.now()}`);

  beforeEach(() => {
    if (fs.existsSync(sentinel)) fs.unlinkSync(sentinel);
  });
  afterEach(() => {
    if (fs.existsSync(sentinel)) fs.unlinkSync(sentinel);
  });

  it("preserves backticks and $() in commit message without shell evaluation", async () => {
    // Keep the message <= 72 chars (CommitChecker trims the first line).
    const malicious = `feat: \`touch ${sentinel}\``;
    expect(malicious.length).toBeLessThanOrEqual(72);
    const repo = initRepo();
    fs.writeFileSync(path.join(repo, "change.txt"), "x");

    const checker = makeChecker(repo, malicious);
    const result = await checker.check({
      link: "build",
      task_id: asTaskId("task-x"),
      task_title: "t",
      task_description: "d",
    });

    expect(result).not.toBeNull();
    expect(result!.message).toBe(malicious);
    expect(fs.existsSync(sentinel)).toBe(false);
    const log = execFileSync("git", ["log", "-1", "--pretty=%B"], {
      cwd: repo,
      encoding: "utf-8",
    }).trim();
    expect(log).toBe(malicious);
  });

  it("preserves embedded double quotes verbatim", async () => {
    const tricky = `feat: he said "hi" and ' bye`;
    const repo = initRepo();
    fs.writeFileSync(path.join(repo, "change.txt"), "x");

    const checker = makeChecker(repo, tricky);
    const result = await checker.check({
      link: "build",
      task_id: asTaskId("task-y"),
      task_title: "t",
      task_description: "d",
    });

    expect(result).not.toBeNull();
    expect(result!.message).toBe(tricky);
    const log = execFileSync("git", ["log", "-1", "--pretty=%B"], {
      cwd: repo,
      encoding: "utf-8",
    }).trim();
    expect(log).toBe(tricky);
  });
});
